/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ArtistaController;
import controller.HistoricoController;
import controller.MusicaController;
import controller.MusicaCurtidaController;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manager.ManagerSession;
import model.MusicaCurtida;
import model.Usuario;

/**
 *
 * @author Masashi
 */
public class Home extends javax.swing.JFrame {
    
    private HistoricoController historicoController = new HistoricoController();
    private MusicaController musicaController = new MusicaController();
    private ArtistaController artistaController = new ArtistaController();
    Usuario usuarioAutenticado = null;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        usuarioAutenticado = ManagerSession.getInstance().getCurrentUser();
        bemvindo.setText("Bem-vindo, " + usuarioAutenticado.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscarHome = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHome = new javax.swing.JTable();
        botaoPlaylist = new javax.swing.JButton();
        botaoHistorico = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bemvindo = new javax.swing.JLabel();
        curtirMusica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("spotifei");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Pesquisar:");

        botaoBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        tabelaHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Artista", "Música", "Álbum", "Gênero", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaHome);

        botaoPlaylist.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoPlaylist.setText("Playlists");
        botaoPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlaylistActionPerformed(evt);
            }
        });

        botaoHistorico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoHistorico.setText("Histórico");
        botaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHistoricoActionPerformed(evt);
            }
        });

        bemvindo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bemvindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bemvindo.setText("Bem-vindo");

        curtirMusica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        curtirMusica.setText("Curtir");
        curtirMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curtirMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarHome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(botaoHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(curtirMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(bemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curtirMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String busca = buscarHome.getText().trim();
        if (busca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Busca não pode ser vazia!", "Erro de Validação", JOptionPane.ERROR_MESSAGE); 
            return;
        }
      
        if (usuarioAutenticado != null) {
            historicoController.registrarBusca(usuarioAutenticado.getId(), busca);
        }
        DefaultTableModel tabela = (DefaultTableModel) tabelaHome.getModel();
        tabela.setRowCount(0); 
        List<model.Musica> musicasPorNome = musicaController.buscarPorNome(busca);

       
        List<model.Musica> musicasPorGenero = musicaController.buscarPorGenero(busca);

       
        List<model.Musica> musicasPorArtista = Collections.emptyList();
        model.Artista artista = artistaController.buscarPorNomeArtistico(busca);
        if (artista != null) {
            musicasPorArtista = new MusicaController().buscarPorArtistaId(artista.getId());
        }

        
        List<model.Musica> resultadoFinal = new java.util.ArrayList<>();
        for (model.Musica m : musicasPorNome) if (!resultadoFinal.contains(m)) resultadoFinal.add(m);
        for (model.Musica m : musicasPorGenero) if (!resultadoFinal.contains(m)) resultadoFinal.add(m);
        for (model.Musica m : musicasPorArtista) if (!resultadoFinal.contains(m)) resultadoFinal.add(m);

        
        for (model.Musica musica : resultadoFinal) {
            String artistaNome = "";
            if (musica.getArtistaId() > 0) {
                model.Artista art = artistaController.buscarPorId(musica.getArtistaId());
                artistaNome = art != null ? art.getNomeArtistico() : "";
            }
            tabela.addRow(new Object[] {
                artistaNome,
                musica.getNome(),
                musica.getAlbum(),
                musica.getGenero(),
                musica.getId() 
            });
        }

        if (resultadoFinal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum resultado encontrado para \"" + busca + "\".");
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed
    

    
    private void botaoPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlaylistActionPerformed
        VPlaylist tela = new VPlaylist();
            tela.setLocationRelativeTo(null); 
            tela.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_botaoPlaylistActionPerformed

    private void botaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHistoricoActionPerformed
        Historico tela = new Historico();
            tela.setLocationRelativeTo(null); 
            tela.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_botaoHistoricoActionPerformed

    private void curtirMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curtirMusicaActionPerformed
    int selectedRow = tabelaHome.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma música na tabela para curtir.", "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
        return;
    }
    int musicaId;
        try {
            musicaId = (int) tabelaHome.getValueAt(selectedRow, 4); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não foi possível obter o ID da música selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int usuarioId = usuarioAutenticado.getId();

        MusicaCurtidaController musicaCurtidaController = new MusicaCurtidaController(); 
        if (musicaCurtidaController.curtido(usuarioId, musicaId)) {
            JOptionPane.showMessageDialog(this, "Você já curtiu esta música.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        MusicaCurtida curtida = musicaCurtidaController.curtirMusica(usuarioId, musicaId);
        if (curtida != null) {
            JOptionPane.showMessageDialog(this, "Música curtida!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao curtir música.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_curtirMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemvindo;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoHistorico;
    private javax.swing.JButton botaoPlaylist;
    private javax.swing.JTextField buscarHome;
    private javax.swing.JButton curtirMusica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHome;
    // End of variables declaration//GEN-END:variables
}
